export const FETCH_USER_PENDING = 'FETCH_USER_PENDING';
export const FETCH_USER_FUFILLED = 'FETCH_USER_FUFILLED';
export const FETCH_USER_REJECTED = 'FETCH_USER_REJECTED';
export const FETCH_QUESTIONS_PENDING = 'FETCH_QUESTIONS_PENDING';
export const FETCH_QUESTIONS_REJECTED = 'FETCH_QUESTIONS_REJECTED';