//user types
export const VERIFY_JWT_TOKEN_SUCCESS = 'VERIFY_JWT_TOKEN_SUCCESS';
export const VERIFY_JWT_TOKEN_FAIL = 'VERIFY_JWT_TOKEN_FAIL';
export const FETCH_USER_PENDING = 'FETCH_USER_PENDING';
export const FETCH_USER_FUFILLED = 'FETCH_USER_FUFILLED';
export const FETCH_USER_REJECTED = 'FETCH_USER_REJECTED';
export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR';

//question types
export const FETCH_QUESTIONS_PENDING = 'FETCH_QUESTIONS_PENDING';
export const FETCH_QUESTIONS_FUFILLED = 'FETCH_QUESTIONS_FUFILLED';
export const FETCH_QUESTIONS_REJECTED = 'FETCH_QUESTIONS_REJECTED';
export const CLEAR_QUESTION__ERROR = 'CLEAR_QUESTION_ERROR';
export const SET_QUESTION = 'SET_QUESTION';
export const SET_OPTION = 'SET_OPTION';
export const SET_ANSWER = 'SET_ANSWER';
export const UPLOAD_QUESTION_PENDING = 'UPLOAD_QUESTION_PENDING';
export const UPLOAD_QUESTION_SUCCESS = 'UPLOAD_QUESTION_SUCCESS';
export const UPLOAD_QUESTION_FAILED = 'UPLOAD_QUESTION_FAILED';
export const UPLOAD_QUESTION_ERROR = 'UPLOAD_QUESTION_ERROR';

//level types
export const FETCH_LEVEL_PENDING = 'FETCH_LEVEL_PENDING';
export const FETCH_LEVEL_FUFILLED = 'FETCH_LEVEL_FUFILLED';
export const FETCH_LEVEL_REJECTED = 'FETCH_LEVEL_REJECTED';
export const UPLOAD_LEVEL_PENDING = 'UPLOAD_LEVEL_PENDING';
export const UPLOAD_LEVEL_FUFILLED = 'UPLOAD_LEVEL_FUFILLED';
export const UPLOAD_LEVEL_REJECTED = 'UPLOAD_LEVEL_REJECTED';

//subject types
export const UPLOAD_SUBJECT_PENDING = 'UPLOAD_SUBJECT_PENDING';
export const UPLOAD_SUBJECT_FUFILLED = 'UPLOAD_SUBJECT_FUFILLED';
export const UPLOAD_SUBJECT_REJECTED = 'UPLOAD_SUBJECT_REJECTED';
export const FETCH_SUBJECT_FUFILLED = 'FETCH_SUBJECT_FUFILLED';
export const FETCH_SUBJECT_REJECTED = 'FETCH_SUBJECT_REJECTED';


//modal types
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const TOGGLE_NESTED_MODAL = 'TOGGLE_NESTED_MODAL';


